// Writes src/app/version.ts with the app version, which is simply the number of
// git commits on this project. Run automatically before start/build/watch/test
// via npm "pre" hooks, so the displayed version always matches the checkout.
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(scriptDir, '../src/app/version.ts');

/** Total commit count on HEAD, or '0' when git is unavailable (e.g. a tarball build). */
function commitCount() {
  try {
    return execSync('git rev-list --count HEAD', { encoding: 'utf8' }).trim() || '0';
  } catch {
    return '0';
  }
}

const version = commitCount();
const contents = `// Generated by scripts/generate-version.mjs — do not edit by hand.
// The version is the number of git commits on this project.
export const APP_VERSION = '${version}';
`;

writeFileSync(outFile, contents);
console.log(`Wrote APP_VERSION = ${version} to src/app/version.ts`);
