// Writes src/app/version.ts with the app version, which is simply the number of
// git commits on this project. Run automatically before start/build/watch/test
// via npm "pre" hooks, so the displayed version always matches the checkout.
//
// version.ts is committed to the repo so a real number ships even when the build
// environment has no git history (e.g. Firebase App Hosting, which excludes
// .git). When git IS available the count is recomputed exactly; when it is not,
// the previously committed value is preserved rather than reset to 0.
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = dirname(fileURLToPath(import.meta.url));
const outFile = resolve(scriptDir, '../src/app/version.ts');

/** Total commit count on HEAD from git, or null when git/history is unavailable. */
function commitCountFromGit() {
  try {
    const count = execSync('git rev-list --count HEAD', {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    return /^\d+$/.test(count) && count !== '0' ? count : null;
  } catch {
    return null;
  }
}

/** The version already committed in version.ts, so a git-less build keeps it. */
function committedVersion() {
  try {
    const match = readFileSync(outFile, 'utf8').match(/APP_VERSION = '(\d+)'/);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

const version = commitCountFromGit() ?? committedVersion() ?? '0';
const contents = `// Generated by scripts/generate-version.mjs — do not edit by hand.
// The version is the number of git commits on this project.
export const APP_VERSION = '${version}';
`;

writeFileSync(outFile, contents);
console.log(`Wrote APP_VERSION = ${version} to src/app/version.ts`);
